name: Build and Deploy
on: 
  push:
    branches:
      - workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@workflow

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@workflow
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build
